image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - staging
  - production

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  only:
    - develop